"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var country_1 = require("./country");
var Seagames_medal_table_1 = require("./Seagames medal table");
var Vietnam = new country_1.Country('Việt Nam', 70, 46, 44);
var Thailand = new country_1.Country('Thái lan', 27, 24, 44);
var Indonesia = new country_1.Country('Indonesia', 19, 30, 24);
var Philippines = new country_1.Country('Philippines', 21, 27, 38);
var Philippines2 = new country_1.Country('Philippines2', 21, 27, 3);
var Philippines3 = new country_1.Country('Philippines3', 21, 30, 37);
var MedalTable = new Seagames_medal_table_1.SeaGamesMedalTable();
MedalTable.insertCountry(Thailand, Philippines, Indonesia, Vietnam, Philippines2, Philippines3);
MedalTable.listSort();
console.log(MedalTable);
